# Generated by Django 4.0 on 2021-12-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=256)),
                ('address', models.CharField(blank=True, db_index=True, max_length=512)),
                ('date', models.CharField(blank=True, db_index=True, max_length=128)),
                ('lat', models.CharField(blank=True, max_length=16)),
                ('long', models.CharField(blank=True, max_length=16)),
                ('link', models.CharField(blank=True, max_length=128)),
                ('type', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
