# Generated by Django 4.0 on 2021-12-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, max_length=256)),
                ('type', models.CharField(blank=True, db_index=True, max_length=32)),
            ],
        ),
    ]
